<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions 
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
	xmlns:soapbind="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:types="http://www.fatturapa.gov.it/sdi/ws/ricezione/v1.0/types"
	xmlns:tns="http://www.fatturapa.gov.it/sdi/ws/ricezione/v1.0"
	targetNamespace="http://www.fatturapa.gov.it/sdi/ws/ricezione/v1.0">

	<!-- TIPI -->
	<wsdl:types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			<xsd:import namespace="http://www.fatturapa.gov.it/sdi/ws/ricezione/v1.0/types" schemaLocation="RicezioneTypes_v1.0.xsd"/>
		</xsd:schema>
	</wsdl:types>

	<!-- MESSAGGI -->
	<wsdl:message name="richiestaSdINotificaEsito_Msg">
		<wsdl:part name="parameters" element="types:fileSdI" />
	</wsdl:message>

	<wsdl:message name="rispostaSdINotificaEsito_Msg">
		<wsdl:part name="parameters" element="types:rispostaSdINotificaEsito" />
	</wsdl:message>

	<!-- PORT TYPE -->
	<wsdl:portType name="SdIRiceviNotifica">
		<wsdl:operation name="NotificaEsito">
			<wsdl:input message="tns:richiestaSdINotificaEsito_Msg" />
			<wsdl:output message="tns:rispostaSdINotificaEsito_Msg" />
		</wsdl:operation>
	</wsdl:portType>

	<!-- PORT BINDING -->
	<wsdl:binding name="SdIRiceviNotifica_binding" type="tns:SdIRiceviNotifica">
		<soapbind:binding style="document" transport="http://schemas.xmlsoap.org/soap/http" />

		<wsdl:operation name="NotificaEsito">
			<soapbind:operation soapAction="http://www.fatturapa.it/SdIRicezioneNotifiche/NotificaEsito" />
			<wsdl:input>
				<soapbind:body use="literal" />
			</wsdl:input>
			<wsdl:output>
				<soapbind:body use="literal" />
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>

	<wsdl:service name="SdIRiceviNotifica_service">
		<wsdl:port name="SdIRiceviNotifica_port" binding="tns:SdIRiceviNotifica_binding">
			<soapbind:address location="http://servizi.fatturapa.it/ricevi_notifica" />
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
